# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "full", # <browse>
  "date1", # <browse>
  "date2", # <browse>
  "size", # <browse>
  "name", # <browse>
  "type", # <browse>
  "path", # <peek>
  "compressed_size", # <peek>
  "uncompressed_size", # <peek>
  "zip", # <peek>
  "path", # <dispense>
  NULL
))
