
# Scrape download links ---------------------------------------------------

html <- rvest::read_html("https://download.cms.gov/nppes/NPI_Files.html")

names <- html |>
  rvest::html_elements("li") |>
  rvest::html_text2()

links <- html |>
  rvest::html_elements("a") |>
  rvest::html_attr("href")

prefix <- "https://download.cms.gov/nppes"

df <- tibble::tribble(
  ~name,    ~link,
  names[4], links[5],
  names[5], links[6],
  names[6], links[7],
  names[7], links[8]) |>
  dplyr::mutate(link = stringr::str_replace(link, ".", prefix)) |>
  tidyr::separate_wider_delim(name, delim = " - ",
                              names = c("names", "desc", "date_format"),
                              too_few = "align_start", too_many = "merge") |>
  tidyr::unite("description", names:desc, remove = TRUE, sep = " ")


# Unzip files to directory ------------------------------------------------

url <- df$link[1]
path_zip <- here::here("D:/nppes")
destfile <- "nppes.zip"

# download zip
curl::curl_download(url, destfile = paste(path_zip, destfile, sep = "/"))

files_nppes <- zip::zip_list("D:/nppes/nppes.zip") |>
  tibble::tibble() |>
  dplyr::mutate(compressed_size = prettyunits::pretty_bytes(compressed_size, style = "nopad"),
                uncompressed_size = prettyunits::pretty_bytes(uncompressed_size, style = "nopad"))


zip::unzip(zipfile = "D:/nppes/nppes.zip", files = files_nppes$filename[[1]], exdir = "D:/nppes")
zip::unzip(zipfile = "D:/nppes/nppes.zip", files = files_nppes$filename[[2]], exdir = "D:/nppes")
zip::unzip(zipfile = "D:/nppes/nppes.zip", files = files_nppes$filename[[3]], exdir = "D:/nppes")
zip::unzip(zipfile = "D:/nppes/nppes.zip", files = files_nppes$filename[[4]], exdir = "D:/nppes")
zip::unzip(zipfile = "D:/nppes/nppes.zip", files = files_nppes$filename[[5]], exdir = "D:/nppes")
zip::unzip(zipfile = "D:/nppes/nppes.zip", files = files_nppes$filename[[6]], exdir = "D:/nppes")
zip::unzip(zipfile = "D:/nppes/nppes.zip", files = files_nppes$filename[[7]], exdir = "D:/nppes")
zip::unzip(zipfile = "D:/nppes/nppes.zip", files = files_nppes$filename[[8]], exdir = "D:/nppes")

# apply map_df() to iterate read_csv over files
#data <- purrr::map_df(paste(path_zip, files, sep = "/"),
#readr::read_csv,
## additional params to read_csv here)



# Load, clean data --------------------------------------------------------

nppes_dataset <- arrow::open_dataset(sources = "D:/nppes/npidata_pfile_20050523-20230312.csv",
                                     schema = arrow::schema(
                                       "NPI" = arrow::string(),
                                       "Entity Type Code" = arrow::string(),
                                       "Replacement NPI" = arrow::string(),
                                       "Employer Identification Number (EIN)" = arrow::string(),
                                       "Provider Organization Name (Legal Business Name)" = arrow::string(),
                                       "Provider Last Name (Legal Name)" = arrow::string(),
                                       "Provider First Name" = arrow::string(),
                                       "Provider Middle Name" = arrow::string(),
                                       "Provider Name Prefix Text" = arrow::string(),
                                       "Provider Name Suffix Text" = arrow::string(),
                                       "Provider Credential Text" = arrow::string(),
                                       "Provider Other Organization Name" = arrow::string(),
                                       "Provider Other Organization Name Type Code" = arrow::string(),
                                       "Provider Other Last Name" = arrow::string(),
                                       "Provider Other First Name" = arrow::string(),
                                       "Provider Other Middle Name" = arrow::string(),
                                       "Provider Other Name Prefix Text" = arrow::string(),
                                       "Provider Other Name Suffix Text" = arrow::string(),
                                       "Provider Other Credential Text" = arrow::string(),
                                       "Provider Other Last Name Type Code" = arrow::string(),
                                       "Provider First Line Business Mailing Address" = arrow::string(),
                                       "Provider Second Line Business Mailing Address" = arrow::string(),
                                       "Provider Business Mailing Address City Name" = arrow::string(),
                                       "Provider Business Mailing Address State Name" = arrow::string(),
                                       "Provider Business Mailing Address Postal Code" = arrow::string(),
                                       "Provider Business Mailing Address Country Code (If outside U.S.)" = arrow::string(),
                                       "Provider Business Mailing Address Telephone Number" = arrow::string(),
                                       "Provider Business Mailing Address Fax Number" = arrow::string(),
                                       "Provider First Line Business Practice Location Address" = arrow::string(),
                                       "Provider Second Line Business Practice Location Address" = arrow::string(),
                                       "Provider Business Practice Location Address City Name" = arrow::string(),
                                       "Provider Business Practice Location Address State Name" = arrow::string(),
                                       "Provider Business Practice Location Address Postal Code" = arrow::string(),
                                       "Provider Business Practice Location Address Country Code (If outside U.S.)" = arrow::string(),
                                       "Provider Business Practice Location Address Telephone Number" = arrow::string(),
                                       "Provider Business Practice Location Address Fax Number" = arrow::string(),
                                       "Provider Enumeration Date" = arrow::string(),
                                       "Last Update Date" = arrow::string(),
                                       "NPI Deactivation Reason Code" = arrow::string(),
                                       "NPI Deactivation Date" = arrow::string(),
                                       "NPI Reactivation Date" = arrow::string(),
                                       "Provider Gender Code" = arrow::string(),
                                       "Authorized Official Last Name" = arrow::string(),
                                       "Authorized Official First Name" = arrow::string(),
                                       "Authorized Official Middle Name" = arrow::string(),
                                       "Authorized Official Title or Position" = arrow::string(),
                                       "Authorized Official Telephone Number" = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_1" = arrow::string(),
                                       "Provider License Number_1" = arrow::string(),
                                       "Provider License Number State Code_1" = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_1" = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_2" = arrow::string(),
                                       "Provider License Number_2" = arrow::string(),
                                       "Provider License Number State Code_2" = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_2" = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_3" = arrow::string(),
                                       "Provider License Number_3" = arrow::string(),
                                       "Provider License Number State Code_3" = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_3"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_4 "           = arrow::string(),
                                       "Provider License Number_4"                      = arrow::string(),
                                       "Provider License Number State Code_4"           = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_4"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_5"            = arrow::string(),
                                       "Provider License Number_5"                      = arrow::string(),
                                       "Provider License Number State Code_5"           = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_5"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_6"            = arrow::string(),
                                       "Provider License Number_6"                      = arrow::string(),
                                       "Provider License Number State Code_6"           = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_6"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_7"            = arrow::string(),
                                       "Provider License Number_7"                      = arrow::string(),
                                       "Provider License Number State Code_7"           = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_7"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_8"            = arrow::string(),
                                       "Provider License Number_8"                      = arrow::string(),
                                       "Provider License Number State Code_8"           = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_8"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_9"            = arrow::string(),
                                       "Provider License Number_9"                      = arrow::string(),
                                       "Provider License Number State Code_9"           = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_9"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_10"           = arrow::string(),
                                       "Provider License Number_10"                     = arrow::string(),
                                       "Provider License Number State Code_10"          = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_10" = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_11"           = arrow::string(),
                                       "Provider License Number_11"                     = arrow::string(),
                                       "Provider License Number State Code_11"          = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_11" = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_12"           = arrow::string(),
                                       "Provider License Number_12"                     = arrow::string(),
                                       "Provider License Number State Code_12"          = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_12" = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_13"           = arrow::string(),
                                       "Provider License Number_13"                     = arrow::string(),
                                       "Provider License Number State Code_13"          = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_13" = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_14"           = arrow::string(),
                                       "Provider License Number_14"                     = arrow::string(),
                                       "Provider License Number State Code_14"          = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_14" = arrow::string(),
                                       "Healthcare Provider Taxonomy Code_15"           = arrow::string(),
                                       "Provider License Number_15"                     = arrow::string(),
                                       "Provider License Number State Code_15"          = arrow::string(),
                                       "Healthcare Provider Primary Taxonomy Switch_15" = arrow::string(),
                                       "Other Provider Identifier_1"            = arrow::string(),
                                       "Other Provider Identifier Type Code_1"  = arrow::string(),
                                       "Other Provider Identifier State_1"      = arrow::string(),
                                       "Other Provider Identifier Issuer_1"     = arrow::string(),
                                       "Other Provider Identifier_2"            = arrow::string(),
                                       "Other Provider Identifier Type Code_2"  = arrow::string(),
                                       "Other Provider Identifier State_2"      = arrow::string(),
                                       "Other Provider Identifier Issuer_2"     = arrow::string(),
                                       "Other Provider Identifier_3"            = arrow::string(),
                                       "Other Provider Identifier Type Code_3"  = arrow::string(),
                                       "Other Provider Identifier State_3"      = arrow::string(),
                                       "Other Provider Identifier Issuer_3"     = arrow::string(),
                                       "Other Provider Identifier_4"            = arrow::string(),
                                       "Other Provider Identifier Type Code_4"  = arrow::string(),
                                       "Other Provider Identifier State_4"      = arrow::string(),
                                       "Other Provider Identifier Issuer_4"     = arrow::string(),
                                       "Other Provider Identifier_5"            = arrow::string(),
                                       "Other Provider Identifier Type Code_5"  = arrow::string(),
                                       "Other Provider Identifier State_5"      = arrow::string(),
                                       "Other Provider Identifier Issuer_5"     = arrow::string(),
                                       "Other Provider Identifier_6"            = arrow::string(),
                                       "Other Provider Identifier Type Code_6"  = arrow::string(),
                                       "Other Provider Identifier State_6"      = arrow::string(),
                                       "Other Provider Identifier Issuer_6"     = arrow::string(),
                                       "Other Provider Identifier_7"            = arrow::string(),
                                       "Other Provider Identifier Type Code_7"  = arrow::string(),
                                       "Other Provider Identifier State_7"      = arrow::string(),
                                       "Other Provider Identifier Issuer_7"     = arrow::string(),
                                       "Other Provider Identifier_8"            = arrow::string(),
                                       "Other Provider Identifier Type Code_8"  = arrow::string(),
                                       "Other Provider Identifier State_8"      = arrow::string(),
                                       "Other Provider Identifier Issuer_8"     = arrow::string(),
                                       "Other Provider Identifier_9"            = arrow::string(),
                                       "Other Provider Identifier Type Code_9"  = arrow::string(),
                                       "Other Provider Identifier State_9"      = arrow::string(),
                                       "Other Provider Identifier Issuer_9"     = arrow::string(),
                                       "Other Provider Identifier_10"           = arrow::string(),
                                       "Other Provider Identifier Type Code_10" = arrow::string(),
                                       "Other Provider Identifier State_10"     = arrow::string(),
                                       "Other Provider Identifier Issuer_10"    = arrow::string(),
                                       "Other Provider Identifier_11"           = arrow::string(),
                                       "Other Provider Identifier Type Code_11" = arrow::string(),
                                       "Other Provider Identifier State_11"     = arrow::string(),
                                       "Other Provider Identifier Issuer_11"    = arrow::string(),
                                       "Other Provider Identifier_12"           = arrow::string(),
                                       "Other Provider Identifier Type Code_12" = arrow::string(),
                                       "Other Provider Identifier State_12"     = arrow::string(),
                                       "Other Provider Identifier Issuer_12"    = arrow::string(),
                                       "Other Provider Identifier_13"           = arrow::string(),
                                       "Other Provider Identifier Type Code_13" = arrow::string(),
                                       "Other Provider Identifier State_13"     = arrow::string(),
                                       "Other Provider Identifier Issuer_13"    = arrow::string(),
                                       "Other Provider Identifier_14"           = arrow::string(),
                                       "Other Provider Identifier Type Code_14" = arrow::string(),
                                       "Other Provider Identifier State_14"     = arrow::string(),
                                       "Other Provider Identifier Issuer_14"    = arrow::string(),
                                       "Other Provider Identifier_15"           = arrow::string(),
                                       "Other Provider Identifier Type Code_15" = arrow::string(),
                                       "Other Provider Identifier State_15"     = arrow::string(),
                                       "Other Provider Identifier Issuer_15"    = arrow::string(),
                                       "Other Provider Identifier_16"           = arrow::string(),
                                       "Other Provider Identifier Type Code_16" = arrow::string(),
                                       "Other Provider Identifier State_16"     = arrow::string(),
                                       "Other Provider Identifier Issuer_16"    = arrow::string(),
                                       "Other Provider Identifier_17"           = arrow::string(),
                                       "Other Provider Identifier Type Code_17" = arrow::string(),
                                       "Other Provider Identifier State_17"     = arrow::string(),
                                       "Other Provider Identifier Issuer_17"    = arrow::string(),
                                       "Other Provider Identifier_18"           = arrow::string(),
                                       "Other Provider Identifier Type Code_18" = arrow::string(),
                                       "Other Provider Identifier State_18"     = arrow::string(),
                                       "Other Provider Identifier Issuer_18"    = arrow::string(),
                                       "Other Provider Identifier_19"           = arrow::string(),
                                       "Other Provider Identifier Type Code_19" = arrow::string(),
                                       "Other Provider Identifier State_19"     = arrow::string(),
                                       "Other Provider Identifier Issuer_19"    = arrow::string(),
                                       "Other Provider Identifier_20"           = arrow::string(),
                                       "Other Provider Identifier Type Code_20" = arrow::string(),
                                       "Other Provider Identifier State_20"     = arrow::string(),
                                       "Other Provider Identifier Issuer_20"    = arrow::string(),
                                       "Other Provider Identifier_21"           = arrow::string(),
                                       "Other Provider Identifier Type Code_21" = arrow::string(),
                                       "Other Provider Identifier State_21"     = arrow::string(),
                                       "Other Provider Identifier Issuer_21"    = arrow::string(),
                                       "Other Provider Identifier_22"           = arrow::string(),
                                       "Other Provider Identifier Type Code_22" = arrow::string(),
                                       "Other Provider Identifier State_22"     = arrow::string(),
                                       "Other Provider Identifier Issuer_22"    = arrow::string(),
                                       "Other Provider Identifier_23"           = arrow::string(),
                                       "Other Provider Identifier Type Code_23" = arrow::string(),
                                       "Other Provider Identifier State_23"     = arrow::string(),
                                       "Other Provider Identifier Issuer_23"    = arrow::string(),
                                       "Other Provider Identifier_24"           = arrow::string(),
                                       "Other Provider Identifier Type Code_24" = arrow::string(),
                                       "Other Provider Identifier State_24"     = arrow::string(),
                                       "Other Provider Identifier Issuer_24"    = arrow::string(),
                                       "Other Provider Identifier_25"           = arrow::string(),
                                       "Other Provider Identifier Type Code_25" = arrow::string(),
                                       "Other Provider Identifier State_25"     = arrow::string(),
                                       "Other Provider Identifier Issuer_25"    = arrow::string(),
                                       "Other Provider Identifier_26"           = arrow::string(),
                                       "Other Provider Identifier Type Code_26" = arrow::string(),
                                       "Other Provider Identifier State_26"     = arrow::string(),
                                       "Other Provider Identifier Issuer_26"    = arrow::string(),
                                       "Other Provider Identifier_27"           = arrow::string(),
                                       "Other Provider Identifier Type Code_27" = arrow::string(),
                                       "Other Provider Identifier State_27"     = arrow::string(),
                                       "Other Provider Identifier Issuer_27"    = arrow::string(),
                                       "Other Provider Identifier_28"           = arrow::string(),
                                       "Other Provider Identifier Type Code_28" = arrow::string(),
                                       "Other Provider Identifier State_28"     = arrow::string(),
                                       "Other Provider Identifier Issuer_28"    = arrow::string(),
                                       "Other Provider Identifier_29"           = arrow::string(),
                                       "Other Provider Identifier Type Code_29" = arrow::string(),
                                       "Other Provider Identifier State_29"     = arrow::string(),
                                       "Other Provider Identifier Issuer_29"    = arrow::string(),
                                       "Other Provider Identifier_30"           = arrow::string(),
                                       "Other Provider Identifier Type Code_30" = arrow::string(),
                                       "Other Provider Identifier State_30"     = arrow::string(),
                                       "Other Provider Identifier Issuer_30"    = arrow::string(),
                                       "Other Provider Identifier_31"           = arrow::string(),
                                       "Other Provider Identifier Type Code_31" = arrow::string(),
                                       "Other Provider Identifier State_31"     = arrow::string(),
                                       "Other Provider Identifier Issuer_31"    = arrow::string(),
                                       "Other Provider Identifier_32"           = arrow::string(),
                                       "Other Provider Identifier Type Code_32" = arrow::string(),
                                       "Other Provider Identifier State_32"     = arrow::string(),
                                       "Other Provider Identifier Issuer_32"    = arrow::string(),
                                       "Other Provider Identifier_33"           = arrow::string(),
                                       "Other Provider Identifier Type Code_33" = arrow::string(),
                                       "Other Provider Identifier State_33"     = arrow::string(),
                                       "Other Provider Identifier Issuer_33"    = arrow::string(),
                                       "Other Provider Identifier_34"           = arrow::string(),
                                       "Other Provider Identifier Type Code_34" = arrow::string(),
                                       "Other Provider Identifier State_34"     = arrow::string(),
                                       "Other Provider Identifier Issuer_34"    = arrow::string(),
                                       "Other Provider Identifier_35"           = arrow::string(),
                                       "Other Provider Identifier Type Code_35" = arrow::string(),
                                       "Other Provider Identifier State_35"     = arrow::string(),
                                       "Other Provider Identifier Issuer_35"    = arrow::string(),
                                       "Other Provider Identifier_36"           = arrow::string(),
                                       "Other Provider Identifier Type Code_36" = arrow::string(),
                                       "Other Provider Identifier State_36"     = arrow::string(),
                                       "Other Provider Identifier Issuer_36"    = arrow::string(),
                                       "Other Provider Identifier_37"           = arrow::string(),
                                       "Other Provider Identifier Type Code_37" = arrow::string(),
                                       "Other Provider Identifier State_37"     = arrow::string(),
                                       "Other Provider Identifier Issuer_37"    = arrow::string(),
                                       "Other Provider Identifier_38"           = arrow::string(),
                                       "Other Provider Identifier Type Code_38" = arrow::string(),
                                       "Other Provider Identifier State_38"     = arrow::string(),
                                       "Other Provider Identifier Issuer_38"    = arrow::string(),
                                       "Other Provider Identifier_39"           = arrow::string(),
                                       "Other Provider Identifier Type Code_39" = arrow::string(),
                                       "Other Provider Identifier State_39"     = arrow::string(),
                                       "Other Provider Identifier Issuer_39"    = arrow::string(),
                                       "Other Provider Identifier_40"           = arrow::string(),
                                       "Other Provider Identifier Type Code_40" = arrow::string(),
                                       "Other Provider Identifier State_40"     = arrow::string(),
                                       "Other Provider Identifier Issuer_40"    = arrow::string(),
                                       "Other Provider Identifier_41"           = arrow::string(),
                                       "Other Provider Identifier Type Code_41" = arrow::string(),
                                       "Other Provider Identifier State_41"     = arrow::string(),
                                       "Other Provider Identifier Issuer_41"    = arrow::string(),
                                       "Other Provider Identifier_42"           = arrow::string(),
                                       "Other Provider Identifier Type Code_42" = arrow::string(),
                                       "Other Provider Identifier State_42"     = arrow::string(),
                                       "Other Provider Identifier Issuer_42"    = arrow::string(),
                                       "Other Provider Identifier_43"           = arrow::string(),
                                       "Other Provider Identifier Type Code_43" = arrow::string(),
                                       "Other Provider Identifier State_43"     = arrow::string(),
                                       "Other Provider Identifier Issuer_43"    = arrow::string(),
                                       "Other Provider Identifier_44"           = arrow::string(),
                                       "Other Provider Identifier Type Code_44" = arrow::string(),
                                       "Other Provider Identifier State_44"     = arrow::string(),
                                       "Other Provider Identifier Issuer_44"    = arrow::string(),
                                       "Other Provider Identifier_45"           = arrow::string(),
                                       "Other Provider Identifier Type Code_45" = arrow::string(),
                                       "Other Provider Identifier State_45"     = arrow::string(),
                                       "Other Provider Identifier Issuer_45"    = arrow::string(),
                                       "Other Provider Identifier_46"           = arrow::string(),
                                       "Other Provider Identifier Type Code_46" = arrow::string(),
                                       "Other Provider Identifier State_46"     = arrow::string(),
                                       "Other Provider Identifier Issuer_46"    = arrow::string(),
                                       "Other Provider Identifier_47"           = arrow::string(),
                                       "Other Provider Identifier Type Code_47" = arrow::string(),
                                       "Other Provider Identifier State_47"     = arrow::string(),
                                       "Other Provider Identifier Issuer_47"    = arrow::string(),
                                       "Other Provider Identifier_48"           = arrow::string(),
                                       "Other Provider Identifier Type Code_48" = arrow::string(),
                                       "Other Provider Identifier State_48"     = arrow::string(),
                                       "Other Provider Identifier Issuer_48"    = arrow::string(),
                                       "Other Provider Identifier_49"           = arrow::string(),
                                       "Other Provider Identifier Type Code_49" = arrow::string(),
                                       "Other Provider Identifier State_49"     = arrow::string(),
                                       "Other Provider Identifier Issuer_49"    = arrow::string(),
                                       "Other Provider Identifier_50"           = arrow::string(),
                                       "Other Provider Identifier Type Code_50" = arrow::string(),
                                       "Other Provider Identifier State_50"     = arrow::string(),
                                       "Other Provider Identifier Issuer_50"    = arrow::string(),
                                       "Is Sole Proprietor" = arrow::string(),
                                       "Is Organization Subpart" = arrow::string(),
                                       "Parent Organization LBN" = arrow::string(),
                                       "Parent Organization TIN" = arrow::string(),
                                       "Authorized Official Name Prefix Text" = arrow::string(),
                                       "Authorized Official Name Suffix Text" = arrow::string(),
                                       "Authorized Official Credential Text" = arrow::string(),
                                       "Healthcare Provider Taxonomy Group_1"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Group_2"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Group_3"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Group_4"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Group_5"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Group_6"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Group_7"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Group_8"  = arrow::string(),
                                       "Healthcare Provider Taxonomy Group_9"  = arrow::string(),
                                       'Healthcare Provider Taxonomy Group_10' = arrow::string(),
                                       'Healthcare Provider Taxonomy Group_11' = arrow::string(),
                                       'Healthcare Provider Taxonomy Group_12' = arrow::string(),
                                       'Healthcare Provider Taxonomy Group_13' = arrow::string(),
                                       'Healthcare Provider Taxonomy Group_14' = arrow::string(),
                                       'Healthcare Provider Taxonomy Group_15' = arrow::string(),
                                       "Certification Date" = arrow::string()),
                                     format = "csv")

# nppes_header <- arrow::read_csv_arrow("D:/nppes/npidata_pfile_20050523-20230312_fileheader.csv") |>
#   janitor::clean_names() |> dplyr::collect()

nppes_dataset <- dplyr::rename_with(nppes_dataset, ~ tolower(gsub(" ", "_", .x, fixed = TRUE)))
nppes_dataset <- dplyr::rename_with(nppes_dataset, ~ tolower(gsub("(", "", .x, fixed = TRUE)))
nppes_dataset <- dplyr::rename_with(nppes_dataset, ~ tolower(gsub(")", "", .x, fixed = TRUE)))
nppes_dataset <- nppes_dataset |> dplyr::filter(npi != "NPI") |> dplyr::filter(entity_type_code != "")



nppes_dataset |>
  dplyr::anti_join()
dplyr::slice_head(n = 547) |>
  #arrow::to_duckdb() |>
  dplyr::collect() |>
  print(n = 1000)

arrow::write_arrow(nppes_dataset, "D:/nppes/parquet", partition)


arrow::write_dataset(nppes_dataset,
                     path = "D:/nppes/arrow",
                     format = "arrow",
                     partitioning = c("provider_business_practice_location_address_state_name", "entity_type_code"))
